---
    - name: Add PHP 5.6 apt-repository from Ondřej Surý
      apt_repository: repo='ppa:ondrej/php5-5.6'

    - name: Update apt cache
      apt: update-cache=yes cache_valid_time=86400
      sudo: yes

    - name: install basic packages
      sudo: yes
      apt: pkg={{ item }} state=latest
      tags: [packages]
      with_items:
        - curl
        - vim
        - libxslt1-dev
        - libxml2-dev
        - unzip
        - python-pip
        - python-psycopg2
        - git
        - ntp

    - name: install PHP 5
      sudo: yes
      apt: pkg={{ item }} state=latest
      tags: [packages]
      with_items:
        - php5

    - name: Check NTP service to make sure it's running
      service: name=ntp state=started enabled=yes
      sudo: yes
